# Generated by Django 4.0 on 2022-05-29 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('age', models.IntegerField(default=0)),
                ('salary', models.IntegerField(default=0)),
                ('date', models.DateField()),
            ],
        ),
    ]
